### ISSUE TITLE
Check whether the package.json within /site is necessary

### ISSUE THREAD

**Issue by pjcevans** [codingforeveryone/codingforeveryone.github.io#22]
As it's causing an issue at jekyll / bundle install - Also in in current [PR](https://github.com/codingforeveryone/codingforeveryone.github.io/pull/21) I have renamed it to prevent this from happening this time + in the future

Out of interest this was the [log file](https://gist.github.com/pjcevans/53a48b6b048519c0b570c819fedd6ff6) generated

**Comment by jwhchambers** [comment]
@pjcevans It isn't needed. I have removed it now!

**Comment by pjcevans** [comment]
Great, thanks for clearing that up - I'll remove the .bak version from the latest branch then

**Comment by samhstn** [comment]
@pjcevans @jwhchambers Just so you know the reason that it wasn't working was because there was a trailing comma on line 24 check the line [here](https://github.com/codingforeveryone/codingforeveryone.github.io/commit/208b004bcf2ec843a9117da9f78d484f360f8171). If you just removed the comma it would have worked

Generally a node project should have a package.json file in the root, it is the first thing a node developer will look at when they look at a node project. But since we are just using the site directory for reference it doesn't really matter
